const KEY="member2_CareerHub_v2";
const DATA=[
{id:1,name:"Python Developer Path",category:"Python",rating:4.9,level:"Beginner → Intermediate",image:"https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1000&q=85",skills:["Python","OOP","SQL"],action:"Start Learning",details:"Build Python fundamentals through OOP, SQL, automation and portfolio projects."},
{id:2,name:"Frontend Developer Path",category:"Web Development",rating:4.8,level:"Beginner → Advanced",image:"https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1000&q=85",skills:["HTML","CSS","JavaScript"],action:"Build Skills",details:"Learn modern HTML, CSS and JavaScript while building responsive web projects."},
{id:3,name:"Software Engineering Internship",category:"Internship",rating:4.7,level:"Student",image:"https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=1000&q=85",skills:["DSA","Git","Projects"],action:"Apply",details:"Prepare for software internships with DSA, Git, teamwork and project practice."},
{id:4,name:"Data Analyst Starter",category:"Data",rating:4.8,level:"Beginner",image:"https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1000&q=85",skills:["Excel","SQL","Python"],action:"Start Learning",details:"Start with spreadsheets, SQL and Python-based data analysis projects."},
{id:5,name:"UI/UX Internship",category:"Design",rating:4.6,level:"Student",image:"https://images.unsplash.com/photo-1559028012-481c04fa702d?w=1000&q=85",skills:["Figma","UX","UI"],action:"Apply",details:"Practice user research, wireframes, prototypes and interface design."},
{id:6,name:"JavaScript Projects",category:"Web Development",rating:4.9,level:"Intermediate",image:"https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=1000&q=85",skills:["JavaScript","DOM","APIs"],action:"Build Project",details:"Strengthen JavaScript by building practical DOM and API projects."},
{id:7,name:"Java Developer Path",category:"Programming",rating:4.7,level:"Intermediate",image:"https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=1000&q=85",skills:["Java","OOP","DSA"],action:"Start Learning",details:"Develop Java programming skills with OOP, DSA and application projects."},
{id:8,name:"Cybersecurity Starter",category:"Security",rating:4.8,level:"Beginner",image:"https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=1000&q=85",skills:["Networks","Linux","Security"],action:"Start Learning",details:"Understand networks, Linux and core cybersecurity concepts."},
{id:9,name:"Cloud Fundamentals",category:"Cloud",rating:4.7,level:"Beginner",image:"https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1000&q=85",skills:["Cloud","Linux","DevOps"],action:"Build Skills",details:"Learn cloud basics, Linux, deployment and DevOps workflows."},
{id:10,name:"AI & ML Starter",category:"AI / ML",rating:4.9,level:"Intermediate",image:"https://images.unsplash.com/photo-1555255707-c07966088b7b?w=1000&q=85",skills:["Python","ML","NumPy"],action:"Start Learning",details:"Explore Python, NumPy and machine-learning fundamentals through small projects."},
{id:11,name:"Product Design Internship",category:"Design",rating:4.7,level:"Student",image:"https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1000&q=85",skills:["Figma","Research","Prototyping"],action:"Apply",details:"Build product-design experience through research, prototypes and case studies."},
{id:12,name:"Backend Developer Internship",category:"Internship",rating:4.8,level:"Student",image:"https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1000&q=85",skills:["APIs","SQL","Git"],action:"Apply",details:"Practice APIs, databases and Git while preparing for backend internships."}
];
let state;
try{state=JSON.parse(localStorage.getItem(KEY)||"null")}catch(e){state=null}
state=state&&typeof state==="object"?state:{};
state.favorites=Array.isArray(state.favorites)?state.favorites:[];
state.saved=Array.isArray(state.saved)?state.saved:[];
state.applications=Array.isArray(state.applications)?state.applications:[];
state.tasks=Array.isArray(state.tasks)?state.tasks:[];
state.dark=!!state.dark;
const $=s=>document.querySelector(s);
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function toast(m){const t=document.createElement("div");t.className="toast";t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),1600)}
function favorite(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();render()}
function closeModal(){$("#modal").classList.remove("show")}
function action(id){const x=DATA.find(a=>a.id===id);if(!x)return;if(x.category==="Internship"){if(!state.applications.includes(id))state.applications.push(id);toast("Application saved ✓")}else{if(!state.saved.includes(id))state.saved.push(id);toast("Saved to Career Workspace ✓")}save();render()}
function details(id){const x=DATA.find(a=>a.id===id);if(!x)return;$("#modalTitle").textContent=x.name;$("#modalContent").innerHTML=`<div class="detail"><img src="${x.image}" onerror="this.style.display='none'"><div><div class="eyebrow">${x.category}</div><h2>${x.name}</h2><p>★ ${x.rating} · ${x.level}</p><p>${x.details}</p><div class="chips">${x.skills.map(s=>`<span class="chip">${s}</span>`).join("")}</div><button class="btn primary" onclick="action(${x.id});closeModal()">${x.action}</button><button class="btn" onclick="favorite(${x.id});closeModal()">♡ Save</button></div></div>`;$("#modal").classList.add("show")}
function task(){const n=prompt("Career task");if(!n)return;state.tasks.push({name:n,done:false});save();work();toast("Task added")}
function done(i){if(!state.tasks[i])return;state.tasks[i].done=!state.tasks[i].done;save();work()}
function card(x){return `<article class="card"><div class="imgbox"><img src="${x.image}" alt="${x.name}" onerror="this.style.display='none'"><button class="heart ${state.favorites.includes(x.id)?"on":""}" onclick="favorite(${x.id})">${state.favorites.includes(x.id)?"♥":"♡"}</button></div><div class="cardbody"><div class="eyebrow">${x.category}</div><h3>${x.name}</h3><div class="muted">${x.level}</div><div class="meta"><span class="rating">★ ${x.rating}</span><span>${x.skills[0]}</span></div><div class="actions"><button class="btn" onclick="details(${x.id})">View Details</button><button class="btn primary" onclick="action(${x.id})">${x.action}</button></div></div></article>`}
function work(){const valid=id=>DATA.find(a=>a.id===id);const saved=state.saved.filter(valid).map(id=>{const x=valid(id);return `<div class="rowitem"><img class="thumb" src="${x.image}" onerror="this.style.display='none'"><div class="grow"><h4>${x.name}</h4><p>Saved path · ${x.skills.join(" · ")}</p></div><button class="btn" onclick="details(${x.id})">Open</button></div>`}).join("");const apps=state.applications.filter(valid).map(id=>{const x=valid(id);return `<div class="rowitem"><img class="thumb" src="${x.image}" onerror="this.style.display='none'"><div class="grow"><h4>${x.name}</h4><p>Application status: Applied</p></div><button class="btn" onclick="toast('Application tracked')">Track</button></div>`}).join("");const tasks=state.tasks.map((x,i)=>`<div class="rowitem"><input type="checkbox" ${x.done?"checked":""} onchange="done(${i})"><div class="grow">${x.name}</div></div>`).join("");$("#work").innerHTML=(saved||'<div class="empty">Save a career path to start.</div>')+`<h3>Applications</h3>`+(apps||'<div class="empty">No applications yet.</div>')+`<h3>My Tasks</h3>`+(tasks||'<div class="empty">No tasks yet.</div>')+`<button class="btn primary" onclick="task()">＋ Add Career Task</button>`}
function render(){const q=$("#search").value.trim().toLowerCase(),cat=document.querySelector(".pill.active")?.dataset.cat||"All";let list=DATA.filter(x=>(cat==="All"||x.category===cat)&&JSON.stringify(x).toLowerCase().includes(q));if($("#sort").value==="rating")list.sort((a,b)=>b.rating-a.rating);if($("#sort").value==="name")list.sort((a,b)=>a.name.localeCompare(b.name));$("#count").textContent=`Showing ${list.length} opportunities`;$("#cards").innerHTML=list.map(card).join("")||'<div class="empty">No opportunities found.</div>';$ ("#favCount").textContent=state.favorites.length;$("#workCount").textContent=state.saved.length+state.applications.length;work()}
document.querySelectorAll(".pill").forEach(b=>b.onclick=()=>{document.querySelectorAll(".pill").forEach(x=>x.classList.remove("active"));b.classList.add("active");render()});
$("#search").oninput=render;$("#sort").onchange=render;$("#theme").onclick=()=>{state.dark=!state.dark;document.body.classList.toggle("dark",state.dark);save()};$("#workbtn").onclick=()=>$("#workspace").scrollIntoView({behavior:"smooth"});$("#close").onclick=closeModal;$("#modal").onclick=e=>{if(e.target.id==="modal")closeModal()};$("#fav").onclick=()=>toast(state.favorites.length+" favorites");document.body.classList.toggle("dark",state.dark);render();
